config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create]

  resources :habits, only: [:create] do
    resources :goals, only: [:new, :show, :edit]
  end

  resources :goals, only: [:create, :index, :update, :destroy]

  resources :categories, only: [:new, :create, :index] do
    resources :habits, only: [:index, :new]
  end

  post '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'

  get '/home' => 'users#home'

  post '/completed_habit/:id' => 'goals#completed_habit', as: 'completed_habit'

  get '/greatest_user' => 'users#greatest_user'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :habits

  scope :alphabetize, -> { order(name: :asc) }

  def popular_habits_in_category
    Habit.popular_habits.select { |h| h.category == self }
  end
end

app/models/completion_date.rb
class CompletionDate < ApplicationRecord
  belongs_to :goal

end

app/models/goal.rb
class Goal < ApplicationRecord
  validates :description, presence: true
  validates :start_date, presence: true

  belongs_to :user
  belongs_to :habit
  has_many :completion_dates, :dependent => :destroy

  def goal_completed_today?(date)
    self.completion_dates.each do |completion_date|
      if completion_date.date.localtime.to_date == date
        return true
      end
    end
    false
  end

  def complete_goal_today
    self.update(days_completed: self.days_completed += 1)
    completion_date = CompletionDate.new(date: Time.now.localtime)
    self.completion_dates << completion_date
  end

  def start_date_in_future?
    self.start_date.to_date > Time.now.localtime.to_date
  end

  def goal_finished?
    self.days_completed >= 66
  end 

end

app/models/habit.rb
class Habit < ApplicationRecord
  validates :name, presence: true

  belongs_to :category
  has_many :goals
  has_many :users, through: :goals

  def self.popular_habits
    select { |h| h.users.count >= 5 }
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness:true
  validates :name, presence: true

  has_many :goals
  has_many :habits, through: :goals

  def num_of_goals_for_habit(habit)
    goals_for_habit = self.goals.where(habit_id: habit.id)
    goals_for_habit.count
  end

  def unique_habits
    self.habits.uniq { |h| h.name }
  end

  def self.user_with_most_goals
    user = self.joins(:goals).group(:user_id).order('COUNT(goals.id) DESC').limit(1)
    user.first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    User.find(session[:user_id])
  end

  def require_login
    redirect_to new_session_path unless session.include? :user_id
  end

  def login(user)
    session[:user_id] = user.id
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def index
    @categories = Category.alphabetize
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end


end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_login

  def new
    @goal = Goal.new(habit_id: params[:habit_id])
  end

  def create
    @goal = Goal.new(goal_params)
    if @goal.save
      redirect_to goals_path
    else
      render :new
    end
  end

  def index
    @goals = current_user.goals
  end

  def show
    @goal = find_goal
  end

  def edit
    @goal = find_goal
  end

  def update
    @goal = find_goal
    @goal.update(goal_params)
    redirect_to goals_path
  end

  def completed_habit
    @goal = find_goal
    if @goal.goal_completed_today?(date_today)
      flash[:message] = "You have already completed this habit today!"
      redirect_to habit_goal_path(@goal.habit, @goal)
    else
      @goal.complete_goal_today
      redirect_to habit_goal_path(@goal.habit, @goal)
    end
  end

  def destroy
    find_goal.destroy
    redirect_to goals_path
  end

  private

  def goal_params
    params.require(:goal).permit(:description, :user_id, :habit_id, :start_date)
  end

  def date_today
    Time.now.localtime.to_date
  end

  def find_goal
    Goal.find(params[:id])
  end


end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :require_login

  def new
    @habit = Habit.new(category_id: params[:category_id])
  end

  def create
    @habit = Habit.new(habit_params)
    if @habit.save
      redirect_to category_habits_path(@habit.category_id)
    else
      render :new
    end
  end

  def index
    @category = Category.find(params[:category_id])
    @habits = @category.habits
  end

  private

  def habit_params
    params.require(:habit).permit(:name, :category_id)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    if auth
      @user = User.find_or_create_by(email: auth['info']['email']) do |u|
       u.name = auth['info']['name']
       u.password = SecureRandom.hex(8)
      end
      login(@user)
      redirect_to home_path
    else
      @user = User.find_by(email: params[:email])
      if @user && @user.authenticate(params[:password])
        login(@user)
        redirect_to home_path
      else
        flash.now[:message] = "Incorrect e-mail or password"
        render :new
      end
    end
  end

  def destroy
    session.delete :user_id
    redirect_to new_session_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to home_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    if logged_in? && current_user == @user
      render :show
    else
      redirect_to new_session_path
    end
  end

  def home
  end

  def greatest_user
    @user = User.user_with_most_goals
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper

  def readable_date(goal)
    goal.start_date.strftime("%B %d, %Y")
  end

  def completion_percentage(goal)
    today = Time.now.localtime.to_date
    start = goal.start_date.to_date
    elapsed_days = [(today - start + 1).to_i, 1].max
    [((goal.days_completed.to_f / elapsed_days) * 100), 100].min.round(2)
  end

  def days_left_to_form_habit(goal)
    66 - goal.days_completed
  end

  def days_until_start(goal)
    (goal.start_date.to_date - Time.now.localtime.to_date).to_i
  end

end

app/helpers/habits_helper.rb
module HabitsHelper

  def category_has_popular_habits?(category)
    !category.popular_habits_in_category.empty?
  end

  def category_has_habits?(category)
    !category.habits.empty?
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="container text-center error_messages">
    <h3>Please fix the following errors:</h3>
    <ul class="list-group">
      <% model.errors.full_messages.each do |message| %>
        <li class="list-group-item">
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_facebook_login.html.erb
<div class="container text-center">
  <h3>OR</h3>
</div>

<div class="container text-center">
  <%= link_to('Log in with Facebook!', '/auth/facebook', method: :post, :class => "badge badge-light") %>
</div>

app/views/categories/index.html.erb
<div class="container text-center">


  <h1>Habit Categories</h1>

  <ul class="list-group">
    <% @categories.each do |category| %>
      <li class="list-group-item">
        <%= link_to category.name, category_habits_path(category) %>
      </li>
    <% end %>
  </ul>

  <%= link_to "Create New Category", new_category_path, :class => "badge badge-pill badge-dark w-50" %>
</div>

app/views/categories/new.html.erb
<%= render :partial => 'application/error_messages', :locals => {:model => @category} %>

<div class="container text-center">
  <h1>Create a Category</h1>
</div>

<div class="container">
  <%= form_for @category do |f| %>
    <div class="form-group row">
      <%= f.label :name, :class => "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, :class => "form-control" %>
      </div>
    </div>
    <div class="col text-center">
      <%= f.submit "Create Category", :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/goals/_form.html.erb
<div class="container">
  <%= form_for(goal) do |f| %>
    <div class="form-group row">
      <%= f.label :description, :class => "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_field :description, :class => "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :start_date, :class => "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.date_select :start_date, :class => "form-control" %>
      </div>
    </div>
    <%= f.hidden_field :habit_id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="col text-center">
      <%= yield f %>
    </div>
  <% end %>
</div>

app/views/goals/edit.html.erb
<div class="container text-center">
  <h1>Edit This Goal</h1>
</div>

<%= render "form", goal: @goal do |f| %>
  <%= f.submit "Edit Goal", :class => "btn btn-primary" %>
<% end %>

app/views/goals/index.html.erb
<div class="container text-center">

  <h1>My Goals</h1>


  <ol class="list-group text-center">
    <% @goals.each do |goal| %>
      <li class="list-group-item">
        <p class="thick"><%= goal.description %></p>
        <ul class="list-group text-center">
          <li class="list-group-item">
            Start Date: <%= readable_date(goal)%>
          </li>
          <li class="list-group-item">
            <%= link_to "View This Goal", habit_goal_path(goal.habit, goal), :class => "badge badge-pill badge-light w-50" %>
          </li>
          <li class="list-group-item">
            <%= link_to "Edit This Goal", edit_habit_goal_path(goal.habit, goal), :class => "badge badge-pill badge-dark w-50" %>
          </li>
          <li class="list-group-item">
            <%= form_tag goal_path(goal), method: "delete" do %>
              <%= submit_tag "Delete Goal", :class => "btn btn-danger" %>
            <% end %>
          </li>
        </ul>
      </li>
    <% end %>
  </ol>
</div>

app/views/goals/new.html.erb
<%= render :partial => 'application/error_messages', :locals => {:model => @goal} %>

<div class="container text-center">
  <h1>Create a Goal</h1>
</div>

<%= render "form", goal: @goal do |f| %>
  <%= f.submit "Create Goal", :class => "btn btn-primary" %>
<% end %>

app/views/goals/show.html.erb
<div class="container text-center error_messages">
  <%= flash[:message] %>
</div>

<div class="container text-center">
  <h1><%= @goal.description %></h1>



  <p>You have completed <%= @goal.days_completed %> days of this habit</p>

  <p>You have <%= days_left_to_form_habit(@goal) %> days left to solidify your habit</p>

  <p>You have completed your habit <%= completion_percentage(@goal) %>% of the time since you started</p>

  <% if !@goal.start_date_in_future? %>
    <h3>Did you complete your habit today?</h3>
    <%= form_tag completed_habit_path(@goal) do %>
      <%= submit_tag "Habit Completed Today", :class => "btn btn-info" %>
    <% end %>
  <% else %>
    <h3>Your goal starts in <%= days_until_start(@goal) %> day(s)!</h3>
  <% end %>
</div>

<div class="container text-center">
  <% if @goal.goal_finished? %>
    <h3>Congratulations On Completing Your Goal!</h3>
    <iframe src="https://giphy.com/embed/ely3apij36BJhoZ234" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/good-job-congratulations-otter-ely3apij36BJhoZ234">via GIPHY</a></p>
  <% end %>
</div>

app/views/habits/index.html.erb
<div class="container text-center">
  <h1 class="container text-center"><%= @category.name %></h1>

  <% if category_has_popular_habits?(@category) %>
    <h3>Most Popular Habits in this Category</h3>

    <ul class="list-group text-center">
      <% @category.popular_habits_in_category.each do |habit| %>
        <li class="list-group-item">
          <%= habit.name %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% if category_has_habits?(@category) %>
    <h3>All Habits in This Category</h3>

    <ol class="list-group text-center">
      <% @category.habits.each do |habit| %>
        <li class="list-group-item"><%= habit.name %> --- <%= link_to "Create a new goal for this habit", new_habit_goal_path(habit), :class => "badge badge-pill badge-light" %></li>
      <% end %>
    </ol>
  <% end %>

  <%= link_to "Create a New Habit in The #{@category.name} Category", new_category_habit_path(@category), :class => "badge badge-pill badge-dark w-50" %>
</div>

app/views/habits/new.html.erb
<%= render :partial => 'application/error_messages', :locals => {:model => @habit} %>

<div class="container text-center">
  <h1>Create a Habit</h1>
</div>

<div class="container">
  <%= form_for @habit do |f| %>
    <div class="form-group row">
      <%= f.label :name, :class => "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, :class => "form-control" %>
      </div>
    </div>
    <%= f.hidden_field :category_id %>
    <div class="col text-center">
      <%= f.submit "Create Habit", :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Habit Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <h3 class="navbar-brand">Habit Tracker</h3>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
          </li>
          <% if logged_in? %>
            <li class="nav-item">
              <a class="nav-link" href=<%= "/users/#{current_user.id}" %>>My Habits</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/categories">Categories</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/goals">My Goals</a>
            </li>
            <li class="nav-item">
              <%= form_tag logout_path do %>
                <%= submit_tag "Log Out", :class => "btn btn-outline-secondary" %>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="/sessions/new">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users/new">Sign Up</a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/greatest_user.html.erb
<h1>Greatest User</h1>

<p><%= @user.name %> has <%= @user.goals.count %> goals!</p>

app/views/users/home.html.erb
<div class="container text-center">

  <h1>Welcome to Habit Tracker</h1>

  <p>Research shows that it takes about 66 days to create a new habit. Get started today!</p>

</div>

<div class="container text-center">
  <div class="rounded">
      <%= image_tag "home/plant_growing.jpg", :class => "img-fluid w-75" %>
  </div>
</div>

app/views/users/new.html.erb
<%= render :partial => 'application/error_messages', :locals => {:model => @user} %>

<div class="container text-center">
  <h1>Sign Up</h1>
</div>

<div class="container">
  <%= form_for @user do |f| %>
    <div class="form-group row">
      <%= f.label :name, :class => "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, :class => "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :email, :class => "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.text_field :email, :class => "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :password, :class => "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.password_field :password, :class => "form-control" %><br>
      </div>
    </div>
    <div class="col text-center">
      <%= f.submit "Sign Up", :class => "btn btn-primary" %>
    </div>
  <% end %>
  <br>
</div>

<%= render "application/facebook_login" %>

app/views/users/show.html.erb
<div class="container text-center">
  <h1>My Habits</h1>

  <ul class="list-group text-center">
    <% @user.unique_habits.each do |habit| %>
      <li class="list-group-item">
        <p><%= habit.name %><p>
        <p>You have <%= @user.num_of_goals_for_habit(habit) %> goal(s) for this habit </p>
      </li>
    <% end %>
  </ul>

</div>